main:	
	g++ -c -std=c++11 Cannibal.cpp
	g++ -c -std=c++11 Enemy.cpp                 
	g++ -c -std=c++11 Gorilla.cpp
	g++ -c -std=c++11 Jaguar.cpp 
	g++ -c -std=c++11 main.cpp     
	g++ -c -std=c++11 Snake.cpp   
	g++ -c -std=c++11 SquadMember.cpp
	g++ -c -std=c++11 EnemyFactory.cpp
	g++ -c -std=c++11 SnakeFactory.cpp
	g++ -c -std=c++11 GorillaFactory.cpp  
	g++ -c -std=c++11 JaguarFactory.cpp  
	g++ -c -std=c++11 CannibalFactory.cpp  
	g++ -c -std=c++11 AdventureIsland.cpp  
	g++ -c -std=c++11 Memento.cpp   
	g++ -c -std=c++11 careTaker.cpp 	         
	g++ -o main Cannibal.o Enemy.o Gorilla.o Jaguar.o main.o Snake.o SquadMember.o EnemyFactory.o SnakeFactory.o GorillaFactory.o JaguarFactory.o CannibalFactory.o AdventureIsland.o careTaker.o Memento.o
	./main
clean:
	rm *.o main